# Generated by Django 4.1.4 on 2022-12-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.CharField(max_length=30, null=True)),
                ('Region', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Category', models.CharField(max_length=30, null=True)),
                ('Product', models.CharField(max_length=30, null=True)),
                ('Quantity', models.CharField(max_length=30, null=True)),
                ('UnitPrice', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
